name: AutoUpdate

permissions:
  contents: write

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install pandas
          pip install earthengine-api
          pip install requests

      - name: Run Earth Engine Script
        run: python earth_engine.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .

          git commit -m "Auto update methane CSV" || echo "No changes"

          git push